#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-timestamps
Version  : 1.2.0
Release  : 4
URL      : https://rubygems.org/downloads/dm-timestamps-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-timestamps-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-spec
BuildRequires : rubygem-test-unit

%description
= dm-timestamps
DataMapper plugin which adds "magic" to created_at, created_on, et cetera.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-timestamps-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-timestamps.gemspec

%build
gem build rubygem-dm-timestamps.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-timestamps-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-timestamps-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/dm-timestamps.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/lib/dm-timestamps.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/spec/integration/timestamps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-timestamps-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-timestamps-1.2.0.gemspec
